/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package rxjava;


import java.io.FileReader;
import java.io.LineNumberReader;



/**
 * This Example Is Not Yet Finished !!! <br/>
 *
 * @see <a href="https://github.com/ReactiveX/RxJava">RxJava<a>
 */
public class HelloWorld {

    // LineCount WordCount ByteCount
    // 700000 14000000 101222205

    private static final String LOREM_IPSUM_FILE = "O:\\Snippets\\Java\\RxJava\\data\\LoremIpsum.txt";


    /**
     *
     */
    private static void doTheOldWay() {

        int iWordCount = 0;

        try (LineNumberReader lnr = new LineNumberReader(new FileReader(LOREM_IPSUM_FILE))) {

            String strLine = null;

            while (true) {

                strLine = lnr.readLine();

                if (strLine == null) {

                    break;
                }

                iWordCount += strLine.split(" ").length;
            }
        } catch (final Exception ex) {

            System.err.println(ex.toString());
        }

        System.out.println(String.format("WordCount: %s", iWordCount));
    }


    private static void doTheRxJavaWay() {

//        try {
////            final var result = Files.readAllLines(Path.of(LOREM_IPSUM_FILE)).parallelStream().forEach();
////            System.out.println(String.format("Result: %s", result));
//
//        } catch (final IOException ex) {
//            System.err.println(ex.toString());
//        }
    }


    /**
     * @param args
     */
    public static void main( final String[] args ) {

        final var start = System.currentTimeMillis();

//        doTheOldWay();
        doTheRxJavaWay();

        final var stop = System.currentTimeMillis();

        System.out.println(String.format("Time: %s ms", stop - start));
    }
}
